### ISSUE TITLE
An example of a robotic arm manipulating a deformable object ？

### ISSUE THREAD

**Issue by WangXingfang** [InteractiveComputerGraphics/stark#2]
This is a very nice work! But I'm not sure how to add a model of a robotic arm to manipulate a deformable object. 
Can you provide an example of a robotic arm manipulating a deformable object? Thank you very much!

**Comment by JoseAntFer** [comment]
Hello,

apologies for the late reply. _For the time being_ Stark does not come with pre-made systems such as robotic arms, vehicles or human rigs. This is a deliberate decision due to current lack of time to properly support it. Additionally, it is usually the case that pre-built systems do not fulfil everyone needs very well. However, Stark does come with most, if not all, the required building blocks to compose such systems from rigid body joints and motors, FEM volumetric soft bodies and shells, contact and friction, etc.

Best,
José.
